name: time_entry_app
description: "A time entry app for generator commissioning company."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  intl: ^0.18.1
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  shared_preferences: ^2.2.2
  path: ^1.8.3
  google_fonts: ^6.1.0
  table_calendar: ^3.0.9
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
